### ISSUE TITLE
Look up C# properties

### ISSUE THREAD

**Issue by rickspears** [SteveWorcester/DnDCharHelper#1]
https://github.com/SteveWorcester/DnDCharHelper/blob/86b56f666dcf840b3d81f07dc9a7c07834aa2526/DnDCharacterHelper/PlayerStats.cs#L15

Have a constructor that instantiates your property.
Get rid of your get and set methods.

**Comment by rickspears** [comment]
Note, AddStat is fine as-is and does not need to be changed. You will be able to get rid of line 24, though.

**Comment by SteveWorcester** [comment]
code has changed a lot. no longer relevant.
