### ISSUE TITLE
Return IEnumerables instead.

### ISSUE THREAD

**Issue by rickspears** [SteveWorcester/DnDCharHelper#2]
https://github.com/SteveWorcester/DnDCharHelper/blob/86b56f666dcf840b3d81f07dc9a7c07834aa2526/DnDCharacterHelper/SavingThrows.cs#L23

This should be a property, the setter can be private.

**Comment by SteveWorcester** [comment]
changed the three arrays to properties; however, they (mistakenly) have the same reference. trying to fix....

**Comment by SteveWorcester** [comment]
old code. i believe this no longer applies (at least in current context) due to iteration/cleanup.
