### ISSUE TITLE
Override ToString

### ISSUE THREAD

**Issue by rickspears** [SteveWorcester/DnDCharHelper#3]
https://github.com/SteveWorcester/DnDCharHelper/blob/cfad58a1f37ff446ae10a5859d600f4f41af5272/DnDCharacterHelper/PlayerStats.cs#L39

Keep the body roughly the same, get rid of the args, access the properties directly.
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/how-to-override-the-tostring-method

**Comment by SteveWorcester** [comment]
now calling WriteStats without passing any variables from Program. WriteStats pulls getters from its own class.
