### ISSUE TITLE
Use Properties

### ISSUE THREAD

**Issue by rickspears** [SteveWorcester/DnDCharHelper#4]
https://github.com/SteveWorcester/DnDCharHelper/blob/cfad58a1f37ff446ae10a5859d600f4f41af5272/DnDCharacterHelper/PlayerStats.cs#L16-L35

Use properties and Lists.
public List<int> OrigStats { get; set; }

**Comment by rickspears** [comment]
https://stackoverflow.com/questions/434761/array-versus-listt-when-to-use-which

**Comment by SteveWorcester** [comment]
removed  bogus private vars for public getters/setters.
