### ISSUE TITLE
Use foreach here!!!!!

### ISSUE THREAD

**Issue by rickspears** [SteveWorcester/DnDCharHelper#5]
https://github.com/SteveWorcester/DnDCharHelper/blob/cfad58a1f37ff446ae10a5859d600f4f41af5272/DnDCharacterHelper/StatBonus.cs#L18

https://www.dotnetperls.com/foreach

**Comment by SteveWorcester** [comment]
updated to foreach. created a new list for each method and added new modded ints to it.
