### ISSUE TITLE
Use a switch provided a playerRace can be only one race

### ISSUE THREAD

**Issue by rickspears** [SteveWorcester/DnDCharHelper#9]
https://github.com/SteveWorcester/DnDCharHelper/blob/dbf978957f94459005cb992e01324cc932096363/DnDCharacterHelper/RaceBonus.cs#L34-L88

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/switch

It will simplify it a little bit and fix your bug.

**Comment by rickspears** [comment]
Alternatively
if...
elseif...
elseif...
else

**Comment by SteveWorcester** [comment]
Converted to switch using ints as selectors for the switch. Added retries within switch.
